# Generated by Django 5.1.6 on 2025-03-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_attributes_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='media/products', verbose_name='Изображение'),
        ),
    ]
